package Client.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import java.util.Map;
import jetbrains.mps.generator.impl.query.ReductionRuleCondition;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.template.ReductionRuleQueryContext;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static boolean rule_Condition_6_0(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operationType$IuTs), CONCEPTS.CREATE$lU);
  }
  public static boolean rule_Condition_6_1(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operationType$IuTs), CONCEPTS.READ$Dt);
  }
  public static boolean rule_Condition_6_2(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operationType$IuTs), CONCEPTS.UPDATE$mp);
  }
  public static boolean rule_Condition_6_3(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operationType$IuTs), CONCEPTS.DELETE$mS);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_0(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.desktopClientRef$eto8) != null) {
      return "import DesktopApp from './DesktopApp';";
    } else {
      return "";
    }
  }
  public static Object propertyMacro_GetValue_3_1(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.mobileClientRef$e8gI) != null) {
      return "import MobileApp from './MobileApp';";
    } else {
      return "";
    }
  }
  public static Object propertyMacro_GetValue_3_2(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.mobileClientRef$e8gI) != null) {
      return "<MobileApp/>";
    } else {
      return "<p>Mobile app not implemented</p>";
    }
  }
  public static Object propertyMacro_GetValue_3_3(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.desktopClientRef$eto8) != null) {
      return "<DesktopApp/>";
    } else {
      return "<p>Desktop app not implemented</p>";
    }
  }
  public static Object propertyMacro_GetValue_4_0(final PropertyMacroContext _context) {
    return (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.clientType$3QV), CONCEPTS.Desktop$qa) ? "Desktop" : "Mobile");
  }
  public static Object propertyMacro_GetValue_4_1(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.globalState$GNTq)).count() == 0) {
      return "";
    }

    final StringBuilder sb = new StringBuilder();
    ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.globalState$GNTq)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        sb.append(SPropertyOperations.getString(it, PROPS.name$MnvL) + ": null,");
      }
    });
    return sb.toString();

  }
  public static Object propertyMacro_GetValue_4_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_3(final PropertyMacroContext _context) {
    if (SPropertyOperations.getBoolean(_context.getNode(), PROPS.showInNavigation$$7VN)) {
      return "<Nav.Link href='" + SPropertyOperations.getString(_context.getNode(), PROPS.route$ZzY4) + "'>" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + "</Nav.Link>";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_4_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.route$ZzY4);
  }
  public static Object propertyMacro_GetValue_4_5(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_7(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.globalState$lvPQ)).count() == 0) {
      return "";
    }
    final StringBuilder sb = new StringBuilder();
    ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.globalState$lvPQ)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        sb.append(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(it, LINKS.key$tP0O), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + ": this.props." + SPropertyOperations.getString(it, PROPS.state$S_YO) + ",");
      }
    });
    return sb.toString();

  }
  public static Object propertyMacro_GetValue_4_8(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.bff$II$1), LINKS.bff$Qfu7), PROPS.port$NA6D);
  }
  public static Object propertyMacro_GetValue_4_9(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.bff$II$1), LINKS.bff$Qfu7), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_10(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.bffRoute$EPCE);
  }
  public static Object propertyMacro_GetValue_4_11(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_12(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_13(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_14(final PropertyMacroContext _context) {
    if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.clientType$3QV), CONCEPTS.Mobile$b9)) {
      return "MobileApp";
    }
    return "DesktopApp";
  }
  public static Object propertyMacro_GetValue_5_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.text$SwCX), LINKS.keyValuePair$wiKW), PROPS.key$hZTW);
  }
  public static Object propertyMacro_GetValue_5_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.imageSrc$Z23B), LINKS.keyValuePair$wiKW), PROPS.key$hZTW);
  }
  public static Object propertyMacro_GetValue_5_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.title$Z2xD), LINKS.keyValuePair$wiKW), PROPS.key$hZTW);
  }
  public static Object propertyMacro_GetValue_5_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.description$Z3eG), LINKS.keyValuePair$wiKW), PROPS.key$hZTW);
  }
  public static Object propertyMacro_GetValue_5_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.imgSrc$N2gX), LINKS.keyValuePair$wiKW), PROPS.key$hZTW);
  }
  public static Object propertyMacro_GetValue_5_5(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.altText$N9jr);
  }
  public static Object propertyMacro_GetValue_5_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.page$AWDZ), LINKS.page$hgW$), PROPS.route$ZzY4);
  }
  public static Object propertyMacro_GetValue_5_7(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.queryParam$B23m) == null) {
      return "";
    }
    return "?" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.queryParam$B23m), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "=${entity." + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.queryParam$B23m), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "}";
  }
  public static Object propertyMacro_GetValue_5_8(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.text$cLQ3);
  }
  public static Object propertyMacro_GetValue_5_9(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.text$1vWk), LINKS.keyValuePair$wiKW), PROPS.key$hZTW);
  }
  public static Object propertyMacro_GetValue_5_10(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(_context.getNode(), PROPS.variant$G5ci) != null) {
      return SPropertyOperations.getString(_context.getNode(), PROPS.variant$G5ci);
    }
    return "primary";
  }
  public static Object propertyMacro_GetValue_5_11(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.actionOperationRef$Jawr) != null) {
      return "this." + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.actionOperationRef$Jawr), LINKS.actionOperation$Gs7t), PROPS.name$MnvL) + "(entity)";
    }
    return "console.log('Not calling any method')";
  }
  public static Object propertyMacro_GetValue_5_12(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.text$JJNU);
  }
  public static Object propertyMacro_GetValue_5_13(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.actionOperationRef$QQAn), LINKS.actionOperation$Gs7t), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_5_14(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.actionText$hWrW);
  }
  public static Object propertyMacro_GetValue_5_15(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.label$gEnR);
  }
  public static Object propertyMacro_GetValue_5_16(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$xA52);
  }
  public static Object propertyMacro_GetValue_5_17(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$PwZW);
  }
  public static Object propertyMacro_GetValue_5_18(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), PROPS.required$Mh$U) ? "required" : "");
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_1(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.globalStateProps$EeER)).count() == 0) {
      return "";
    }
    final StringBuilder sb = new StringBuilder();
    ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.globalStateProps$EeER)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        sb.append("entityPayload['" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(it, LINKS.key$tP0O), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "'] = this.props." + SPropertyOperations.getString(it, PROPS.state$S_YO) + ";\n");
      }
    });
    return sb.toString();

  }
  public static Object propertyMacro_GetValue_6_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.BFFRef$7dHG), LINKS.bff$Qfu7), PROPS.port$NA6D);
  }
  public static Object propertyMacro_GetValue_6_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.BFFRef$7dHG), LINKS.bff$Qfu7), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.route$Xyfx);
  }
  public static Object propertyMacro_GetValue_6_5(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.stateUpdate$uFWk)).count() != 0) {
      final StringBuilder sb = new StringBuilder();
      ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.stateUpdate$uFWk)).visitAll(new IVisitor<SNode>() {
        public void visit(SNode it) {
          sb.append("this.props.updateGlobalState({'" + SPropertyOperations.getString(it, PROPS.state$S_YO) + "': data." + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(it, LINKS.key$tP0O), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "});\n");
        }
      });
      return sb.toString();
    }

    return "";
  }
  public static Object propertyMacro_GetValue_6_6(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.pageRef$Ees2) != null) {
      return "this.props.history.push('" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.pageRef$Ees2), LINKS.page$hgW$), PROPS.route$ZzY4) + "');";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_6_7(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_8(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.queryParams$XxLv)).count() == 0) {
      return "{}";
    }
    final StringBuilder sb = new StringBuilder();
    ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.queryParams$XxLv)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        sb.append("'" + SPropertyOperations.getString(SLinkOperations.getTarget(it, LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "'" + ",");
      }
    });
    return "_.pick(entity, [" + sb.toString() + "]);";
  }
  public static Object propertyMacro_GetValue_6_9(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.BFFRef$7dHG), LINKS.bff$Qfu7), PROPS.port$NA6D);
  }
  public static Object propertyMacro_GetValue_6_10(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.BFFRef$7dHG), LINKS.bff$Qfu7), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_11(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.route$Xyfx);
  }
  public static Object propertyMacro_GetValue_6_12(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.stateUpdate$uFWk)).count() != 0) {
      final StringBuilder sb = new StringBuilder();
      ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.stateUpdate$uFWk)).visitAll(new IVisitor<SNode>() {
        public void visit(SNode it) {
          sb.append("this.props.updateGlobalState({'" + SPropertyOperations.getString(it, PROPS.state$S_YO) + "': data." + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(it, LINKS.key$tP0O), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "});\n");
        }
      });
      return sb.toString();
    }

    return "";
  }
  public static Object propertyMacro_GetValue_6_13(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.pageRef$Ees2) != null) {
      return "this.props.history.push('" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.pageRef$Ees2), LINKS.page$hgW$), PROPS.route$ZzY4) + "');";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_6_14(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_15(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.queryParams$XxLv)).count() == 0) {
      return "{}";
    }
    final StringBuilder sb = new StringBuilder();
    ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.queryParams$XxLv)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        sb.append("'" + SPropertyOperations.getString(SLinkOperations.getTarget(it, LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "'" + ",");
      }
    });
    return "_.pick(entity, [" + sb.toString() + "]);";
  }
  public static Object propertyMacro_GetValue_6_16(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.globalStateProps$EeER)).count() == 0) {
      return "";
    }
    final StringBuilder sb = new StringBuilder();
    ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.globalStateProps$EeER)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        sb.append("entityPayload['" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(it, LINKS.key$tP0O), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "'] = this.props." + SPropertyOperations.getString(it, PROPS.state$S_YO) + ";\n");
      }
    });
    return sb.toString();
  }
  public static Object propertyMacro_GetValue_6_17(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.BFFRef$7dHG), LINKS.bff$Qfu7), PROPS.port$NA6D);
  }
  public static Object propertyMacro_GetValue_6_18(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.BFFRef$7dHG), LINKS.bff$Qfu7), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_19(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.route$Xyfx);
  }
  public static Object propertyMacro_GetValue_6_20(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.stateUpdate$uFWk)).count() != 0) {
      final StringBuilder sb = new StringBuilder();
      ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.stateUpdate$uFWk)).visitAll(new IVisitor<SNode>() {
        public void visit(SNode it) {
          sb.append("this.props.updateGlobalState({'" + SPropertyOperations.getString(it, PROPS.state$S_YO) + "': data." + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(it, LINKS.key$tP0O), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "});\n");
        }
      });
      return sb.toString();
    }

    return "";
  }
  public static Object propertyMacro_GetValue_6_21(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.pageRef$Ees2) != null) {
      return "this.props.history.push('" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.pageRef$Ees2), LINKS.page$hgW$), PROPS.route$ZzY4) + "');";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_6_22(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_23(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.queryParams$XxLv)).count() == 0) {
      return "{}";
    }
    final StringBuilder sb = new StringBuilder();
    ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.queryParams$XxLv)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        sb.append("'" + SPropertyOperations.getString(SLinkOperations.getTarget(it, LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "'" + ",");
      }
    });
    return "_.pick(entity, [" + sb.toString() + "]);";
  }
  public static Object propertyMacro_GetValue_6_24(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.BFFRef$7dHG), LINKS.bff$Qfu7), PROPS.port$NA6D);
  }
  public static Object propertyMacro_GetValue_6_25(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.BFFRef$7dHG), LINKS.bff$Qfu7), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_26(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.route$Xyfx);
  }
  public static Object propertyMacro_GetValue_6_27(final PropertyMacroContext _context) {
    if (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.stateUpdate$uFWk)).count() != 0) {
      final StringBuilder sb = new StringBuilder();
      ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.stateUpdate$uFWk)).visitAll(new IVisitor<SNode>() {
        public void visit(SNode it) {
          sb.append("this.props.updateGlobalState({'" + SPropertyOperations.getString(it, PROPS.state$S_YO) + "': data." + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(it, LINKS.key$tP0O), LINKS.keyValuePair$wiKW), PROPS.key$hZTW) + "});\n");
        }
      });
      return sb.toString();
    }

    return "";
  }
  public static Object propertyMacro_GetValue_6_28(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.pageRef$Ees2) != null) {
      return "this.props.history.push('" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.pageRef$Ees2), LINKS.page$hgW$), PROPS.route$ZzY4) + "');";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_7_0(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.mobileClientRef$e8gI) != null) {
      return "mv ./MobileApp.jsx src";
    } else {
      return "";
    }
  }
  public static Object propertyMacro_GetValue_7_1(final PropertyMacroContext _context) {
    if (SLinkOperations.getTarget(_context.getNode(), LINKS.desktopClientRef$eto8) != null) {
      return "mv ./DesktopApp.jsx src";
    } else {
      return "";
    }
  }
  public static Iterable<SNode> sourceNodesQuery_4_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.pages$VDa9);
  }
  public static Iterable<SNode> sourceNodesQuery_4_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.pages$VDa9);
  }
  public static Iterable<SNode> sourceNodesQuery_4_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.actions$jz7s);
  }
  public static Iterable<SNode> sourceNodesQuery_4_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.components$N3lx);
  }
  public static Iterable<SNode> sourceNodesQuery_4_4(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(_context.getNode()), CONCEPTS.Page$ov)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getBoolean(it, PROPS.hasState$3vni);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_4_5(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.actions$jz7s);
  }
  public static Iterable<SNode> sourceNodesQuery_4_6(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.components$N3lx);
  }
  public static Iterable<SNode> sourceNodesQuery_4_7(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(_context.getNode()), CONCEPTS.Page$ov)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return !(SPropertyOperations.getBoolean(it, PROPS.hasState$3vni));
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_5_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.action$jijh);
  }
  public static Iterable<SNode> sourceNodesQuery_5_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.inputs$$Sw0);
  }
  private final Map<String, ReductionRuleCondition> rrcMethods = new HashMap<String, ReductionRuleCondition>();
  {
    int i = 0;
    rrcMethods.put("8980703707718891042", new RRC(i++));
    rrcMethods.put("8980703707718901348", new RRC(i++));
    rrcMethods.put("8980703707721372130", new RRC(i++));
    rrcMethods.put("8980703707721391206", new RRC(i++));
  }
  @Override
  @NotNull
  public ReductionRuleCondition getReductionRuleCondition(@NotNull QueryKey identity) {
    ReductionRuleCondition query = identity.forTemplateNode(rrcMethods);
    return (query != null ? query : super.getReductionRuleCondition(identity));
  }
  private static class RRC implements ReductionRuleCondition {
    private final int methodKey;
    public RRC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(ReductionRuleQueryContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.rule_Condition_6_0(ctx);
        case 1:
          return QueriesGenerated.rule_Condition_6_1(ctx);
        case 2:
          return QueriesGenerated.rule_Condition_6_2(ctx);
        case 3:
          return QueriesGenerated.rule_Condition_6_3(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("756716148937253774", new SNsQ(i++));
    snsqMethods.put("756716148937169909", new SNsQ(i++));
    snsqMethods.put("8980703707719689250", new SNsQ(i++));
    snsqMethods.put("3500647199489342826", new SNsQ(i++));
    snsqMethods.put("756716148937758009", new SNsQ(i++));
    snsqMethods.put("3500647199490816362", new SNsQ(i++));
    snsqMethods.put("8036317117598860296", new SNsQ(i++));
    snsqMethods.put("3500647199487195225", new SNsQ(i++));
    snsqMethods.put("756716148943482772", new SNsQ(i++));
    snsqMethods.put("3500647199486134975", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    SourceNodesQuery query = identity.forFunctionNode(snsqMethods);
    return (query != null ? query : super.getSourceNodesQuery(identity));
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_2(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_3(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_4(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_5(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_6(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_7(ctx));
        case 8:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_0(ctx));
        case 9:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_1(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("756716148936437648", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "appName"));
    pvqMethods.put("756716148936429056", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "appName"));
    pvqMethods.put("3500647199483101323", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "desktopImport"));
    pvqMethods.put("3500647199483099369", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "mobileImport"));
    pvqMethods.put("756716148936440451", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "mobileApp"));
    pvqMethods.put("756716148936450560", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "desktopApp"));
    pvqMethods.put("415413067792244270", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("415413067794488458", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "properties"));
    pvqMethods.put("756716148936558295", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("3500647199484432353", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "page"));
    pvqMethods.put("756716148937171386", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "route"));
    pvqMethods.put("756716148937177813", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "page"));
    pvqMethods.put("756716148937760200", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "PageName"));
    pvqMethods.put("1099055542467914608", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "globalStateParams"));
    pvqMethods.put("756716148940646228", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "port"));
    pvqMethods.put("756716148940663298", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "bff"));
    pvqMethods.put("756716148940756691", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "route"));
    pvqMethods.put("756716148937773736", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("3500647199487414933", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "PageName"));
    pvqMethods.put("3500647199487223920", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "title"));
    pvqMethods.put("756716148936531953", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("756716148942939217", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "text"));
    pvqMethods.put("756716148942949196", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "image"));
    pvqMethods.put("756716148942958223", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "title"));
    pvqMethods.put("756716148942965789", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "description"));
    pvqMethods.put("756716148943932545", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "src"));
    pvqMethods.put("756716148943940377", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "altText"));
    pvqMethods.put("756716148944187145", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "route"));
    pvqMethods.put("756716148944187157", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "queryParams"));
    pvqMethods.put("756716148944187198", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "text"));
    pvqMethods.put("756716148944275612", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "key"));
    pvqMethods.put("8980703707719552207", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "variant"));
    pvqMethods.put("8980703707719562260", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "operationName"));
    pvqMethods.put("8980703707719570591", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "text"));
    pvqMethods.put("3500647199486140424", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "onSubmit"));
    pvqMethods.put("3500647199486136885", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "text"));
    pvqMethods.put("3500647199486120124", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "label"));
    pvqMethods.put("3500647199486123904", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "type"));
    pvqMethods.put("3500647199486127460", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("3500647199486130612", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "required"));
    pvqMethods.put("8980703707720159571", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "operationName"));
    pvqMethods.put("1099055542465155614", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "globalStateFetch"));
    pvqMethods.put("8980703707720163989", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "port"));
    pvqMethods.put("8980703707720174359", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "bff"));
    pvqMethods.put("8980703707720184077", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "route"));
    pvqMethods.put("1099055542460053078", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "globalStateUpdate"));
    pvqMethods.put("8036317117600721903", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "redirect"));
    pvqMethods.put("8980703707719807117", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "operationName"));
    pvqMethods.put("8980703707719042712", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "params"));
    pvqMethods.put("8980703707719083595", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "port"));
    pvqMethods.put("8980703707719091734", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "bff"));
    pvqMethods.put("8980703707719101027", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "route"));
    pvqMethods.put("1099055542460199639", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "globalStateUpdate"));
    pvqMethods.put("8036317117599670619", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "redirect"));
    pvqMethods.put("8980703707721372137", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "operationName"));
    pvqMethods.put("8980703707721372149", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "params"));
    pvqMethods.put("1099055542465326826", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "globalStateFetch"));
    pvqMethods.put("8980703707721372211", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "port"));
    pvqMethods.put("8980703707721372224", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "bff"));
    pvqMethods.put("8980703707721372237", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "route"));
    pvqMethods.put("1099055542460208691", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "globalStateUpdate"));
    pvqMethods.put("8036317117600717377", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "redirect"));
    pvqMethods.put("8980703707721391213", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "operationName"));
    pvqMethods.put("8980703707721391225", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "params"));
    pvqMethods.put("8980703707721391287", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "port"));
    pvqMethods.put("8980703707721391300", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "bff"));
    pvqMethods.put("8980703707721391313", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "route"));
    pvqMethods.put("1099055542460218665", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "globalStateUpdate"));
    pvqMethods.put("8036317117600718636", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "redirect"));
    pvqMethods.put("3500647199483104276", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "moveMobile"));
    pvqMethods.put("3500647199483105972", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "moveDesktop"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    PropertyValueQuery query = identity.forTemplateNode(pvqMethods);
    return (query != null ? query : super.getPropertyValueQuery(identity));
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_2_0(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_3_0(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_3_1(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_3_2(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_3_3(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_4_0(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_4_1(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_4_2(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_4_3(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_4_4(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_4_5(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_4_6(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_4_7(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_4_8(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_4_9(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_4_10(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetValue_4_11(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetValue_4_12(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetValue_4_13(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetValue_4_14(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetValue_5_0(ctx);
        case 22:
          return QueriesGenerated.propertyMacro_GetValue_5_1(ctx);
        case 23:
          return QueriesGenerated.propertyMacro_GetValue_5_2(ctx);
        case 24:
          return QueriesGenerated.propertyMacro_GetValue_5_3(ctx);
        case 25:
          return QueriesGenerated.propertyMacro_GetValue_5_4(ctx);
        case 26:
          return QueriesGenerated.propertyMacro_GetValue_5_5(ctx);
        case 27:
          return QueriesGenerated.propertyMacro_GetValue_5_6(ctx);
        case 28:
          return QueriesGenerated.propertyMacro_GetValue_5_7(ctx);
        case 29:
          return QueriesGenerated.propertyMacro_GetValue_5_8(ctx);
        case 30:
          return QueriesGenerated.propertyMacro_GetValue_5_9(ctx);
        case 31:
          return QueriesGenerated.propertyMacro_GetValue_5_10(ctx);
        case 32:
          return QueriesGenerated.propertyMacro_GetValue_5_11(ctx);
        case 33:
          return QueriesGenerated.propertyMacro_GetValue_5_12(ctx);
        case 34:
          return QueriesGenerated.propertyMacro_GetValue_5_13(ctx);
        case 35:
          return QueriesGenerated.propertyMacro_GetValue_5_14(ctx);
        case 36:
          return QueriesGenerated.propertyMacro_GetValue_5_15(ctx);
        case 37:
          return QueriesGenerated.propertyMacro_GetValue_5_16(ctx);
        case 38:
          return QueriesGenerated.propertyMacro_GetValue_5_17(ctx);
        case 39:
          return QueriesGenerated.propertyMacro_GetValue_5_18(ctx);
        case 40:
          return QueriesGenerated.propertyMacro_GetValue_6_0(ctx);
        case 41:
          return QueriesGenerated.propertyMacro_GetValue_6_1(ctx);
        case 42:
          return QueriesGenerated.propertyMacro_GetValue_6_2(ctx);
        case 43:
          return QueriesGenerated.propertyMacro_GetValue_6_3(ctx);
        case 44:
          return QueriesGenerated.propertyMacro_GetValue_6_4(ctx);
        case 45:
          return QueriesGenerated.propertyMacro_GetValue_6_5(ctx);
        case 46:
          return QueriesGenerated.propertyMacro_GetValue_6_6(ctx);
        case 47:
          return QueriesGenerated.propertyMacro_GetValue_6_7(ctx);
        case 48:
          return QueriesGenerated.propertyMacro_GetValue_6_8(ctx);
        case 49:
          return QueriesGenerated.propertyMacro_GetValue_6_9(ctx);
        case 50:
          return QueriesGenerated.propertyMacro_GetValue_6_10(ctx);
        case 51:
          return QueriesGenerated.propertyMacro_GetValue_6_11(ctx);
        case 52:
          return QueriesGenerated.propertyMacro_GetValue_6_12(ctx);
        case 53:
          return QueriesGenerated.propertyMacro_GetValue_6_13(ctx);
        case 54:
          return QueriesGenerated.propertyMacro_GetValue_6_14(ctx);
        case 55:
          return QueriesGenerated.propertyMacro_GetValue_6_15(ctx);
        case 56:
          return QueriesGenerated.propertyMacro_GetValue_6_16(ctx);
        case 57:
          return QueriesGenerated.propertyMacro_GetValue_6_17(ctx);
        case 58:
          return QueriesGenerated.propertyMacro_GetValue_6_18(ctx);
        case 59:
          return QueriesGenerated.propertyMacro_GetValue_6_19(ctx);
        case 60:
          return QueriesGenerated.propertyMacro_GetValue_6_20(ctx);
        case 61:
          return QueriesGenerated.propertyMacro_GetValue_6_21(ctx);
        case 62:
          return QueriesGenerated.propertyMacro_GetValue_6_22(ctx);
        case 63:
          return QueriesGenerated.propertyMacro_GetValue_6_23(ctx);
        case 64:
          return QueriesGenerated.propertyMacro_GetValue_6_24(ctx);
        case 65:
          return QueriesGenerated.propertyMacro_GetValue_6_25(ctx);
        case 66:
          return QueriesGenerated.propertyMacro_GetValue_6_26(ctx);
        case 67:
          return QueriesGenerated.propertyMacro_GetValue_6_27(ctx);
        case 68:
          return QueriesGenerated.propertyMacro_GetValue_6_28(ctx);
        case 69:
          return QueriesGenerated.propertyMacro_GetValue_7_0(ctx);
        case 70:
          return QueriesGenerated.propertyMacro_GetValue_7_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink operationType$IuTs = MetaAdapterFactory.getContainmentLink(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x4151f0e6b1cb88b6L, 0x4151f0e6b1cb88b7L, "operationType");
    /*package*/ static final SContainmentLink desktopClientRef$eto8 = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x56a8c307f66dc0c2L, 0xa806554052709eeL, "desktopClientRef");
    /*package*/ static final SContainmentLink mobileClientRef$e8gI = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x56a8c307f66dc0c2L, 0xa806554052709d3L, "mobileClientRef");
    /*package*/ static final SContainmentLink clientType$3QV = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb0cb4634L, 0x6f7d3aaeb0cb463eL, "clientType");
    /*package*/ static final SContainmentLink globalState$GNTq = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554051c0e0eL, 0x5c3d7fbf4e28b2dL, "globalState");
    /*package*/ static final SContainmentLink globalState$lvPQ = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, 0xf40a1315d300c61L, "globalState");
    /*package*/ static final SContainmentLink key$tP0O = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xf40a1315ccee6edL, 0xf40a1315ccee6f0L, "key");
    /*package*/ static final SReferenceLink keyValuePair$wiKW = MetaAdapterFactory.getReferenceLink(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x624f1b6582e9a400L, 0x624f1b6582e9a401L, "keyValuePair");
    /*package*/ static final SContainmentLink bff$II$1 = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, 0xa806554054870e5L, "bff");
    /*package*/ static final SReferenceLink bff$Qfu7 = MetaAdapterFactory.getReferenceLink(0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0xa80655405469adaL, 0xa80655405469adbL, "bff");
    /*package*/ static final SContainmentLink text$SwCX = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa8065540571b850L, 0xa8065540571b851L, "text");
    /*package*/ static final SContainmentLink imageSrc$Z23B = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa80655405656aa0L, 0xa80655405873006L, "imageSrc");
    /*package*/ static final SContainmentLink title$Z2xD = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa80655405656aa0L, 0xa80655405873008L, "title");
    /*package*/ static final SContainmentLink description$Z3eG = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa80655405656aa0L, 0xa8065540587300bL, "description");
    /*package*/ static final SContainmentLink imgSrc$N2gX = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554059973baL, 0xa806554059973bbL, "imgSrc");
    /*package*/ static final SContainmentLink page$AWDZ = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554058d4e4aL, 0xa806554058d4e4dL, "page");
    /*package*/ static final SReferenceLink page$hgW$ = MetaAdapterFactory.getReferenceLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554051c0e24L, 0xa806554051c7f2eL, "page");
    /*package*/ static final SContainmentLink queryParam$B23m = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554058d4e4aL, 0xa806554058d4e4fL, "queryParam");
    /*package*/ static final SContainmentLink text$1vWk = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554059ff916L, 0xa806554059ff919L, "text");
    /*package*/ static final SContainmentLink actionOperationRef$Jawr = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x7ca1de70bb9a32c7L, 0x7ca1de70bb9a3308L, "actionOperationRef");
    /*package*/ static final SReferenceLink actionOperation$Gs7t = MetaAdapterFactory.getReferenceLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x7ca1de70bb9a32e6L, 0x7ca1de70bb9a32e7L, "actionOperation");
    /*package*/ static final SContainmentLink actionOperationRef$QQAn = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x3094cc14a950da52L, 0x3094cc14a9534c50L, "actionOperationRef");
    /*package*/ static final SContainmentLink globalStateProps$EeER = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xcc684dcdf8dce3bL, 0xf40a1315d092150L, "globalStateProps");
    /*package*/ static final SContainmentLink BFFRef$7dHG = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xcc684dcdf8dce3bL, 0x7ca1de70bb92f8d8L, "BFFRef");
    /*package*/ static final SContainmentLink stateUpdate$uFWk = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xcc684dcdf8dce3bL, 0xf40a1315cbb9cbeL, "stateUpdate");
    /*package*/ static final SContainmentLink pageRef$Ees2 = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xcc684dcdf8dce3bL, 0x6f86bbd718e8ecd6L, "pageRef");
    /*package*/ static final SContainmentLink queryParams$XxLv = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xcc684dcdf8dce3bL, 0xcc684dcdf8dce3eL, "queryParams");
    /*package*/ static final SContainmentLink pages$VDa9 = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554051c0e0eL, 0xa806554052446acL, "pages");
    /*package*/ static final SContainmentLink actions$jz7s = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, 0xcc684dcdf8dde8dL, "actions");
    /*package*/ static final SContainmentLink components$N3lx = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, 0xa806554056d9b14L, "components");
    /*package*/ static final SContainmentLink action$jijh = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa80655405656aa0L, 0xa806554058d5e00L, "action");
    /*package*/ static final SContainmentLink inputs$$Sw0 = MetaAdapterFactory.getContainmentLink(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x3094cc14a950da52L, 0x3094cc14a950da56L, "inputs");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CREATE$lU = MetaAdapterFactory.getConcept(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x4151f0e6b1c7ddb6L, "Microservice.structure.CREATE");
    /*package*/ static final SConcept READ$Dt = MetaAdapterFactory.getConcept(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x4151f0e6b1c74508L, "Microservice.structure.READ");
    /*package*/ static final SConcept UPDATE$mp = MetaAdapterFactory.getConcept(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x4151f0e6b1c7ddb7L, "Microservice.structure.UPDATE");
    /*package*/ static final SConcept DELETE$mS = MetaAdapterFactory.getConcept(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x4151f0e6b1c7ddb8L, "Microservice.structure.DELETE");
    /*package*/ static final SConcept Desktop$qa = MetaAdapterFactory.getConcept(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb0cb464aL, "Client.structure.Desktop");
    /*package*/ static final SConcept Mobile$b9 = MetaAdapterFactory.getConcept(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb0cb4640L, "Client.structure.Mobile");
    /*package*/ static final SConcept Page$ov = MetaAdapterFactory.getConcept(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, "Client.structure.Page");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty showInNavigation$$7VN = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, 0x3094cc14a937fe6eL, "showInNavigation");
    /*package*/ static final SProperty route$ZzY4 = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, 0xa8065540532a932L, "route");
    /*package*/ static final SProperty key$hZTW = MetaAdapterFactory.getProperty(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x1957db2831e8dd8cL, 0x1957db2831e8dd8dL, "key");
    /*package*/ static final SProperty state$S_YO = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xf40a1315ccee6edL, 0xf40a1315cd79adeL, "state");
    /*package*/ static final SProperty port$NA6D = MetaAdapterFactory.getProperty(0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5e52L, 0x45ab0ea3d0ad5e60L, "port");
    /*package*/ static final SProperty bffRoute$EPCE = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, 0xa80655405604912L, "bffRoute");
    /*package*/ static final SProperty altText$N9jr = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554059973baL, 0xa806554059973c4L, "altText");
    /*package*/ static final SProperty text$cLQ3 = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xa806554058d4e4aL, 0xa806554058e8461L, "text");
    /*package*/ static final SProperty variant$G5ci = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x7ca1de70bb9a32c7L, 0x7ca1de70bb9a32c8L, "variant");
    /*package*/ static final SProperty text$JJNU = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x7ca1de70bb9a32c7L, 0x7ca1de70bb9a333eL, "text");
    /*package*/ static final SProperty actionText$hWrW = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x3094cc14a950da52L, 0x3094cc14a9564eceL, "actionText");
    /*package*/ static final SProperty label$gEnR = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x3094cc14a950da53L, 0x3094cc14a950f534L, "label");
    /*package*/ static final SProperty type$xA52 = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x3094cc14a950da53L, 0x3094cc14a950f6ecL, "type");
    /*package*/ static final SProperty name$PwZW = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x3094cc14a950da53L, 0xf40a1315d27ff1fL, "name");
    /*package*/ static final SProperty required$Mh$U = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x3094cc14a950da53L, 0x3094cc14a950f794L, "required");
    /*package*/ static final SProperty route$Xyfx = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0xcc684dcdf8dce3bL, 0xcc684dcdf8dce40L, "route");
    /*package*/ static final SProperty hasState$3vni = MetaAdapterFactory.getProperty(0x48e57d507e0f4c8fL, 0x93fc859018228309L, 0x6f7d3aaeb103b898L, 0x3094cc14a95ae677L, "hasState");
  }
}
