package BFF.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BFF = 0;
  public static final int BFFOperation = 1;
  public static final int Desktop = 2;
  public static final int ISupportedType = 3;
  public static final int Mobile = 4;
  public static final int SupportedType = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x41009928b4904ac3L, 0xb8488158d6c0d5dbL);
    builder.put(0x45ab0ea3d0ad5e52L, BFF);
    builder.put(0x45ab0ea3d0ad5e6bL, BFFOperation);
    builder.put(0x45ab0ea3d0ad5ec6L, Desktop);
    builder.put(0x45ab0ea3d0ad5ecaL, ISupportedType);
    builder.put(0x45ab0ea3d0ad5ec7L, Mobile);
    builder.put(0x45ab0ea3d0ad5ec8L, SupportedType);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
