package BFF.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBFF = createDescriptorForBFF();
  /*package*/ final ConceptDescriptor myConceptBFFOperation = createDescriptorForBFFOperation();
  /*package*/ final ConceptDescriptor myConceptDesktop = createDescriptorForDesktop();
  /*package*/ final ConceptDescriptor myConceptISupportedType = createDescriptorForISupportedType();
  /*package*/ final ConceptDescriptor myConceptMobile = createDescriptorForMobile();
  /*package*/ final ConceptDescriptor myConceptSupportedType = createDescriptorForSupportedType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, "Microservice");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBFF, myConceptBFFOperation, myConceptDesktop, myConceptISupportedType, myConceptMobile, myConceptSupportedType);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BFF:
        return myConceptBFF;
      case LanguageConceptSwitch.BFFOperation:
        return myConceptBFFOperation;
      case LanguageConceptSwitch.Desktop:
        return myConceptDesktop;
      case LanguageConceptSwitch.ISupportedType:
        return myConceptISupportedType;
      case LanguageConceptSwitch.Mobile:
        return myConceptMobile;
      case LanguageConceptSwitch.SupportedType:
        return myConceptSupportedType;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBFF() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BFF", "BFF", 0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5e52L);
    b.class_(false, false, true);
    b.parent(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x2242fe026373f54eL);
    b.parent(0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5ecaL);
    b.origin("r:5258dad9-7f81-478a-88e8-d59dd64939d8(BFF.structure)/5020122306378030674");
    b.version(2);
    b.property("version", 0x45ab0ea3d0ad5e53L).type(PrimitiveTypeId.STRING).origin("5020122306378030675").done();
    b.property("description", 0x45ab0ea3d0ad5e59L).type(PrimitiveTypeId.STRING).origin("5020122306378030681").done();
    b.property("maintainerEmail", 0x45ab0ea3d0ad5e5cL).type(PrimitiveTypeId.STRING).origin("5020122306378030684").done();
    b.property("port", 0x45ab0ea3d0ad5e60L).type(PrimitiveTypeId.STRING).origin("5020122306378030688").done();
    b.aggregate("operations", 0x45ab0ea3d0ad5e72L).target(0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5e6bL).optional(true).ordered(true).multiple(true).origin("5020122306378030706").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBFFOperation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BFF", "BFFOperation", 0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5e6bL);
    b.class_(false, false, false);
    b.parent(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x4151f0e6b1cb88b6L);
    b.parent(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x4151f0e6b1d117cdL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.origin("r:5258dad9-7f81-478a-88e8-d59dd64939d8(BFF.structure)/5020122306378030699");
    b.version(2);
    b.property("route", 0x45ab0ea3d0ad6097L).type(PrimitiveTypeId.STRING).origin("5020122306378031255").done();
    b.property("microserviceRoute", 0x45ab0ea3d0ad609cL).type(PrimitiveTypeId.STRING).origin("5020122306378031260").done();
    b.aggregate("microservice", 0x45ab0ea3d0ad60a0L).target(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x675907eeb91f484bL).optional(true).ordered(true).multiple(false).origin("5020122306378031264").done();
    b.aggregate("entityType", 0x45ab0ea3d0ada300L).target(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x624f1b6582e0e556L).optional(true).ordered(true).multiple(false).origin("5020122306378048256").done();
    b.aggregate("expectedQueryParams", 0x624f1b6582e9a406L).target(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x624f1b6582e9a400L).optional(true).ordered(true).multiple(true).origin("7083910861679076358").done();
    b.aggregate("deliveredQueryParams", 0x45ab0ea3d0ad6322L).target(0xe995fbb60310461aL, 0xbe22cc66f48262f1L, 0x624f1b6582e9a400L).optional(true).ordered(true).multiple(true).origin("5020122306378031906").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDesktop() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BFF", "Desktop", 0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5ec6L);
    b.class_(false, false, false);
    b.super_("BFF.structure.SupportedType", 0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5ec8L);
    b.origin("r:5258dad9-7f81-478a-88e8-d59dd64939d8(BFF.structure)/5020122306378030790");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForISupportedType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BFF", "ISupportedType", 0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5ecaL);
    b.interface_();
    b.origin("r:5258dad9-7f81-478a-88e8-d59dd64939d8(BFF.structure)/5020122306378030794");
    b.version(2);
    b.aggregate("supportedType", 0x45ab0ea3d0ad5ecbL).target(0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5ec8L).optional(true).ordered(true).multiple(false).origin("5020122306378030795").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMobile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BFF", "Mobile", 0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5ec7L);
    b.class_(false, false, false);
    b.super_("BFF.structure.SupportedType", 0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5ec8L);
    b.origin("r:5258dad9-7f81-478a-88e8-d59dd64939d8(BFF.structure)/5020122306378030791");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSupportedType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BFF", "SupportedType", 0x41009928b4904ac3L, 0xb8488158d6c0d5dbL, 0x45ab0ea3d0ad5ec8L);
    b.class_(false, false, false);
    b.origin("r:5258dad9-7f81-478a-88e8-d59dd64939d8(BFF.structure)/5020122306378030792");
    b.version(2);
    return b.create();
  }
}
