package Client.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int ActionOperation = 1;
  public static final int ActionOperationReference = 2;
  public static final int Card = 3;
  public static final int Client = 4;
  public static final int ClientConfig = 5;
  public static final int ClientReference = 6;
  public static final int ClientType = 7;
  public static final int CrudAction = 8;
  public static final int Desktop = 9;
  public static final int Form = 10;
  public static final int IClientType = 11;
  public static final int Image = 12;
  public static final int Input = 13;
  public static final int Link = 14;
  public static final int Mobile = 15;
  public static final int Page = 16;
  public static final int PageReference = 17;
  public static final int Text = 18;
  public static final int Title = 19;
  public static final int UIComponent = 20;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x48e57d507e0f4c8fL, 0x93fc859018228309L);
    builder.put(0xa806554058d4e49L, Action);
    builder.put(0xcc684dcdf8dce3bL, ActionOperation);
    builder.put(0x7ca1de70bb9a32e6L, ActionOperationReference);
    builder.put(0xa80655405656aa0L, Card);
    builder.put(0xa806554051c0e0eL, Client);
    builder.put(0x56a8c307f66dc0c2L, ClientConfig);
    builder.put(0xa8065540525534dL, ClientReference);
    builder.put(0x6f7d3aaeb0cad68bL, ClientType);
    builder.put(0x7ca1de70bb9a32c7L, CrudAction);
    builder.put(0x6f7d3aaeb0cb464aL, Desktop);
    builder.put(0x3094cc14a950da52L, Form);
    builder.put(0x6f7d3aaeb0cb4634L, IClientType);
    builder.put(0xa806554059973baL, Image);
    builder.put(0x3094cc14a950da53L, Input);
    builder.put(0xa806554058d4e4aL, Link);
    builder.put(0x6f7d3aaeb0cb4640L, Mobile);
    builder.put(0x6f7d3aaeb103b898L, Page);
    builder.put(0xa806554051c0e24L, PageReference);
    builder.put(0xa806554059ff916L, Text);
    builder.put(0xa8065540571b850L, Title);
    builder.put(0xa806554053e9bc3L, UIComponent);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
